package GUI;

import DAL.ThuocDAL;
import DTO.*;
import BLL.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import Utils.DBUtils;
import java.util.ArrayList;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import keeptoo.TableActionEvent;

public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form EmpDashBoard
     */
    public Customer() {
        initComponents();
        setLocationRelativeTo(null);
        LoadCustomer(cbll.Load_BLL());

    }
    KhachHangBLL cbll=new KhachHangBLL();
    DefaultTableModel tableModelCustomer;
    private String VAITRO=DangNhap.frmInstance.txt1;
    public void LoadCustomer(ArrayList<KhachHang> dskhach) {
        tableModelCustomer = new DefaultTableModel();
        String title[] = {"Mã Khách hàng","Họ tên","Số điện thoại","Địa chỉ","Điểm tích lũy","Email"};
        tableModelCustomer.setColumnIdentifiers(title);
        KhachHang t=new KhachHang();
        for (int i = 0; i < dskhach.size(); i++) {
            t = dskhach.get(i);
            String MAKH=t.getMAKH();
            String HOTEN=t.getHOTEN();
            String SDT= t.getSODT();
            String DIACHI=t.getDIACHI();
            String DIEMTICHLUY=t.getDIEMTICHLUY();
            String EMAIL=t.getEMAIL();
            Object row[] = {MAKH,HOTEN,SDT,DIACHI,DIEMTICHLUY,EMAIL};
            tableModelCustomer.addRow(row);
        }
        jTableCustomer.setModel(tableModelCustomer);
//         setVisible(true);
    }

    public void LoadCustomerForm(ArrayList<KhachHang> dskhach) {
        KhachHang t =new KhachHang();
        for (int i = 0; i < dskhach.size(); i++) {
            t= dskhach.get(i);
            String MAKH=t.getMAKH();
            String HOTEN=t.getHOTEN();
            String SDT= t.getSODT();
            String DIACHI=t.getDIACHI();
            String DIEMTICHLUY=t.getDIEMTICHLUY();
            String EMAIL=t.getEMAIL();

            txtid.setText(MAKH);
            txtname1.setText(HOTEN);
            txtphone1.setText(SDT);
            txtaddress1.setText(DIACHI);
            txtpoint1.setText(DIEMTICHLUY);
            txtemail1.setText(EMAIL);
            
            txtid1.setText(MAKH);
            txtname3.setText(HOTEN);
            txtphone3.setText(SDT);
            txtaddress3.setText(DIACHI);
            txtpoint3.setText(DIEMTICHLUY);
            txtemail3.setText(EMAIL);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateofbirth = new com.raven.datechooser.DateChooser();
        startdate = new com.raven.datechooser.DateChooser();
        mainpanel = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtTimKiem = new javax.swing.JTextField();
        imgSearch = new javax.swing.JLabel();
        btnTimKiem = new keeptoo.Mybutton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        insert = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lbHoTen = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lbdiachi = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtpoint = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        lbtichluy = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        btnsave = new keeptoo.Mybutton();
        update = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lbHoTen1 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtphone1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lbdiachi1 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        txtpoint1 = new javax.swing.JTextField();
        txtemail1 = new javax.swing.JTextField();
        lbtichluy1 = new javax.swing.JLabel();
        lbemail1 = new javax.swing.JLabel();
        lbHoTen4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnsave1 = new keeptoo.Mybutton();
        delete = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnsave2 = new keeptoo.Mybutton();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        lbHoTen3 = new javax.swing.JLabel();
        txtname3 = new javax.swing.JTextField();
        txtphone3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lbdiachi3 = new javax.swing.JLabel();
        txtaddress3 = new javax.swing.JTextField();
        txtpoint3 = new javax.swing.JTextField();
        txtemail3 = new javax.swing.JTextField();
        lbtichluy3 = new javax.swing.JLabel();
        lbemail3 = new javax.swing.JLabel();
        lbHoTen5 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        lbThuoc = new javax.swing.JLabel();
        imgBack = new javax.swing.JLabel();
        btnBack = new keeptoo.Mybutton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imgInsert = new javax.swing.JLabel();
        imgList = new javax.swing.JLabel();
        btnDSThuoc = new keeptoo.Mybutton();
        btnadd = new keeptoo.Mybutton();
        jLabel16 = new javax.swing.JLabel();
        btnupdate = new keeptoo.Mybutton();

        dateofbirth.setDateFormat("dd/MM/yyyy");
        dateofbirth.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        startdate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 131, 149));
        setMinimumSize(new java.awt.Dimension(1100, 783));

        mainpanel.setBackground(new java.awt.Color(10, 77, 105));
        mainpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 15, 0, new java.awt.Color(8, 131, 149)));
        mainpanel.setForeground(new java.awt.Color(10, 77, 105));
        mainpanel.setMaximumSize(new java.awt.Dimension(1200, 750));
        mainpanel.setMinimumSize(new java.awt.Dimension(1101, 750));
        mainpanel.setPreferredSize(new java.awt.Dimension(1101, 750));
        mainpanel.setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(8, 131, 149));
        kGradientPanel1.setkGradientFocus(550);
        kGradientPanel1.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel1.setLayout(null);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimKiem.setToolTipText("");
        txtTimKiem.setBorder(null);
        txtTimKiem.setName(""); // NOI18N
        txtTimKiem.setOpaque(true);
        kGradientPanel1.add(txtTimKiem);
        txtTimKiem.setBounds(100, 10, 410, 30);

        imgSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        kGradientPanel1.add(imgSearch);
        imgSearch.setBounds(550, 10, 35, 35);

        btnTimKiem.setBorder(null);
        btnTimKiem.setText("    Tìm Kiếm");
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.setFocusable(false);
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setRadius(40);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnTimKiem);
        btnTimKiem.setBounds(540, 10, 140, 40);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(8, 131, 149));

        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCustomer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        insert.setBackground(new java.awt.Color(8, 131, 149));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Thêm Khách Hàng");

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(10, 77, 105)));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 255, 202));
        kGradientPanel2.setkGradientFocus(750);
        kGradientPanel2.setkStartColor(new java.awt.Color(5, 191, 219));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(697, 386));

        lbHoTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen.setText("Họ Tên");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Số điện thoại");

        lbdiachi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbdiachi.setForeground(new java.awt.Color(255, 255, 255));
        lbdiachi.setText("Địa chỉ");

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtpoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbtichluy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtichluy.setForeground(new java.awt.Color(255, 255, 255));
        lbtichluy.setText("Điểm tích lũy");

        lbemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbemail.setForeground(new java.awt.Color(255, 255, 255));
        lbemail.setText("Email");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                            .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbtichluy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(txtpoint))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdiachi))
                .addGap(34, 34, 34)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtichluy)
                    .addComponent(txtpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbemail))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        btnsave.setText("Lưu");
        btnsave.setBorderPainted(false);
        btnsave.setFocusable(false);
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setRadius(39);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertLayout = new javax.swing.GroupLayout(insert);
        insert.setLayout(insertLayout);
        insertLayout.setHorizontalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(825, 825, 825))
        );
        insertLayout.setVerticalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );

        jTabbedPane1.addTab("tab2", insert);

        update.setBackground(new java.awt.Color(8, 131, 149));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Chỉnh Sửa Thông Tin Khách Hàng");

        kGradientPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(10, 77, 105)));
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 255, 202));
        kGradientPanel3.setkGradientFocus(750);
        kGradientPanel3.setkStartColor(new java.awt.Color(5, 191, 219));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(697, 386));
        kGradientPanel3.setLayout(null);

        lbHoTen1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoTen1.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen1.setText("Mã khách hàng");
        kGradientPanel3.add(lbHoTen1);
        lbHoTen1.setBounds(160, 30, 160, 22);

        txtname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtname1);
        txtname1.setBounds(320, 80, 206, 28);

        txtphone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtphone1);
        txtphone1.setBounds(320, 130, 206, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Số điện thoại");
        kGradientPanel3.add(jLabel20);
        jLabel20.setBounds(160, 130, 123, 22);

        lbdiachi1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbdiachi1.setForeground(new java.awt.Color(255, 255, 255));
        lbdiachi1.setText("Địa chỉ");
        kGradientPanel3.add(lbdiachi1);
        lbdiachi1.setBounds(160, 190, 84, 22);

        txtaddress1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtaddress1);
        txtaddress1.setBounds(320, 190, 206, 28);

        txtpoint1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtpoint1);
        txtpoint1.setBounds(320, 250, 206, 28);

        txtemail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtemail1);
        txtemail1.setBounds(320, 308, 206, 28);

        lbtichluy1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtichluy1.setForeground(new java.awt.Color(255, 255, 255));
        lbtichluy1.setText("Điểm tích lũy");
        kGradientPanel3.add(lbtichluy1);
        lbtichluy1.setBounds(163, 253, 140, 22);

        lbemail1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbemail1.setForeground(new java.awt.Color(255, 255, 255));
        lbemail1.setText("Email");
        kGradientPanel3.add(lbemail1);
        lbemail1.setBounds(163, 308, 84, 22);

        lbHoTen4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoTen4.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen4.setText("Họ Tên");
        kGradientPanel3.add(lbHoTen4);
        lbHoTen4.setBounds(160, 80, 84, 22);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel3.add(txtid);
        txtid.setBounds(320, 30, 90, 28);

        btnsave1.setText("Lưu");
        btnsave1.setBorderPainted(false);
        btnsave1.setFocusable(false);
        btnsave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave1.setRadius(39);
        btnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                        .addComponent(btnsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(215, 215, 215))))
            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addComponent(btnsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", update);

        delete.setBackground(new java.awt.Color(8, 131, 149));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Xóa Khách Hàng");

        btnsave2.setText("Xóa dữ liệu");
        btnsave2.setBorderPainted(false);
        btnsave2.setFocusable(false);
        btnsave2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave2.setRadius(39);
        btnsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave2ActionPerformed(evt);
            }
        });

        kGradientPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(10, 77, 105)));
        kGradientPanel7.setkEndColor(new java.awt.Color(0, 255, 202));
        kGradientPanel7.setkGradientFocus(750);
        kGradientPanel7.setkStartColor(new java.awt.Color(5, 191, 219));
        kGradientPanel7.setPreferredSize(new java.awt.Dimension(697, 386));
        kGradientPanel7.setLayout(null);

        lbHoTen3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoTen3.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen3.setText("Mã khách hàng");
        kGradientPanel7.add(lbHoTen3);
        lbHoTen3.setBounds(160, 30, 160, 22);

        txtname3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtname3);
        txtname3.setBounds(320, 80, 206, 28);

        txtphone3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtphone3);
        txtphone3.setBounds(320, 130, 206, 28);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Số điện thoại");
        kGradientPanel7.add(jLabel21);
        jLabel21.setBounds(160, 130, 123, 22);

        lbdiachi3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbdiachi3.setForeground(new java.awt.Color(255, 255, 255));
        lbdiachi3.setText("Địa chỉ");
        kGradientPanel7.add(lbdiachi3);
        lbdiachi3.setBounds(160, 190, 84, 22);

        txtaddress3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtaddress3);
        txtaddress3.setBounds(320, 190, 206, 28);

        txtpoint3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtpoint3);
        txtpoint3.setBounds(320, 250, 206, 28);

        txtemail3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtemail3);
        txtemail3.setBounds(320, 308, 206, 28);

        lbtichluy3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtichluy3.setForeground(new java.awt.Color(255, 255, 255));
        lbtichluy3.setText("Điểm tích lũy");
        kGradientPanel7.add(lbtichluy3);
        lbtichluy3.setBounds(163, 253, 140, 22);

        lbemail3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbemail3.setForeground(new java.awt.Color(255, 255, 255));
        lbemail3.setText("Email");
        kGradientPanel7.add(lbemail3);
        lbemail3.setBounds(163, 308, 84, 22);

        lbHoTen5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoTen5.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen5.setText("Họ Tên");
        kGradientPanel7.add(lbHoTen5);
        lbHoTen5.setBounds(160, 80, 84, 22);

        txtid1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel7.add(txtid1);
        txtid1.setBounds(320, 30, 90, 28);

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayout.createSequentialGroup()
                        .addComponent(btnsave2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))))
            .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(btnsave2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", delete);

        kGradientPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(-50, 50, 830, 530);

        mainpanel.add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 60, 790, 600);

        kGradientPanel4.setBackground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setForeground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel4.setkGradientFocus(50);
        kGradientPanel4.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setMinimumSize(new java.awt.Dimension(20, 690));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(20, 690));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        mainpanel.add(kGradientPanel4);
        kGradientPanel4.setBounds(810, 0, 20, 710);

        kGradientPanel5.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel5.setkGradientFocus(175);
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));

        lbThuoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThuoc.setText("KHÁCH HÀNG");
        lbThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbThuoc.setInheritsPopupMenu(false);

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lbThuoc)
                .addGap(41, 41, 41))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbThuoc.getAccessibleContext().setAccessibleName("");

        mainpanel.add(kGradientPanel5);
        kGradientPanel5.setBounds(830, 180, 250, 70);

        imgBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow.png"))); // NOI18N
        mainpanel.add(imgBack);
        imgBack.setBounds(890, 600, 45, 45);

        btnBack.setBorder(null);
        btnBack.setText("      Quay lại");
        btnBack.setBorderPainted(false);
        btnBack.setColor1(new java.awt.Color(216, 171, 255));
        btnBack.setColor2(new java.awt.Color(3, 137, 255));
        btnBack.setFocusable(false);
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setkGradientFocus(225);
        btnBack.setPreferredSize(new java.awt.Dimension(170, 65));
        btnBack.setRadius(39);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainpanel.add(btnBack);
        btnBack.setBounds(880, 600, 160, 50);

        jPanel8.setBackground(new java.awt.Color(4, 191, 219));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainpanel.add(jPanel8);
        jPanel8.setBounds(0, 50, 810, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        mainpanel.add(jLabel3);
        jLabel3.setBounds(390, 10, 41, 41);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        mainpanel.add(jLabel4);
        jLabel4.setBounds(610, 10, 41, 41);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (5).png"))); // NOI18N
        mainpanel.add(jLabel5);
        jLabel5.setBounds(220, 10, 41, 41);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        mainpanel.add(jLabel7);
        jLabel7.setBounds(870, 30, 171, 120);

        imgInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        mainpanel.add(imgInsert);
        imgInsert.setBounds(890, 360, 43, 43);

        imgList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        mainpanel.add(imgList);
        imgList.setBounds(890, 290, 43, 43);

        btnDSThuoc.setBorder(null);
        btnDSThuoc.setText("        Danh sách");
        btnDSThuoc.setToolTipText("");
        btnDSThuoc.setBorderPainted(false);
        btnDSThuoc.setFocusable(false);
        btnDSThuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDSThuoc.setRadius(39);
        btnDSThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSThuocActionPerformed(evt);
            }
        });
        mainpanel.add(btnDSThuoc);
        btnDSThuoc.setBounds(880, 290, 160, 50);

        btnadd.setText("    Thêm");
        btnadd.setBorderPainted(false);
        btnadd.setFocusable(false);
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setRadius(39);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        mainpanel.add(btnadd);
        btnadd.setBounds(880, 360, 160, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shuffle.png"))); // NOI18N
        mainpanel.add(jLabel16);
        jLabel16.setBounds(890, 430, 43, 50);

        btnupdate.setText("      Chỉnh sửa");
        btnupdate.setBorderPainted(false);
        btnupdate.setFocusable(false);
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setRadius(39);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        mainpanel.add(btnupdate);
        btnupdate.setBounds(880, 430, 160, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if(VAITRO.equals("0")){
            this.dispose();
            ManagerDashBoard m =new ManagerDashBoard();
            m.setVisible(true);
        }else if(VAITRO.equals("1")){
            this.dispose();
            EmpDashBoard m =new EmpDashBoard();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDSThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSThuocActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        LoadCustomer(cbll.Load_BLL());
    }//GEN-LAST:event_btnDSThuocActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        LoadCustomer(cbll.Search_BLL(txtTimKiem.getText()));
        LoadCustomerForm(cbll.Search_BLL(txtTimKiem.getText()));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try {
            if (txtname.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Họ tên không được bỏ trống");
            } else if (txtphone.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không được bỏ trống");
            } else if (txtaddress.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Địa chỉ không được bỏ trống");
            } else if (txtpoint.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Điểm tích không được bỏ trống");
            } else if (txtemail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Email không được bỏ trống");
            } else if (Integer.parseInt(txtpoint.getText())<0) {
                JOptionPane.showMessageDialog(null, "Điểm tích lũy phải là số dương");
            }else {

                boolean check = cbll.Insert(txtname.getText(), txtphone.getText(),txtaddress.getText(),txtpoint.getText(),txtemail.getText());
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtname1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Họ tên không được bỏ trống");
            } else if (txtphone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không được bỏ trống");
            } else if (txtaddress1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Địa chỉ không được bỏ trống");
            } else if (txtpoint1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Điểm tích không được bỏ trống");
            } else if (txtemail1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Email không được bỏ trống");
            } else if (Integer.parseInt(txtpoint1.getText())<0) {
                JOptionPane.showMessageDialog(null, "Điểm tích lũy phải là số dương");
            }else {

                boolean check = cbll.Update(txtid.getText(),txtname1.getText(), txtphone1.getText(),txtaddress1.getText(),txtpoint1.getText(),txtemail1.getText());
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsave1ActionPerformed

    private void btnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave2ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa dữ liệu!", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            try {
                boolean check = cbll.Delete(txtid1.getText(),txtname3.getText(), txtphone3.getText(),txtaddress3.getText(),txtpoint3.getText(),txtemail3.getText());
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnsave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.Mybutton btnBack;
    private keeptoo.Mybutton btnDSThuoc;
    private keeptoo.Mybutton btnTimKiem;
    private keeptoo.Mybutton btnadd;
    private keeptoo.Mybutton btnsave;
    private keeptoo.Mybutton btnsave1;
    private keeptoo.Mybutton btnsave2;
    private keeptoo.Mybutton btnupdate;
    private com.raven.datechooser.DateChooser dateofbirth;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel imgBack;
    private javax.swing.JLabel imgInsert;
    private javax.swing.JLabel imgList;
    private javax.swing.JLabel imgSearch;
    private javax.swing.JPanel insert;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCustomer;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbHoTen1;
    private javax.swing.JLabel lbHoTen3;
    private javax.swing.JLabel lbHoTen4;
    private javax.swing.JLabel lbHoTen5;
    private javax.swing.JLabel lbThuoc;
    private javax.swing.JLabel lbdiachi;
    private javax.swing.JLabel lbdiachi1;
    private javax.swing.JLabel lbdiachi3;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbemail1;
    private javax.swing.JLabel lbemail3;
    private javax.swing.JLabel lbtichluy;
    private javax.swing.JLabel lbtichluy1;
    private javax.swing.JLabel lbtichluy3;
    private javax.swing.JPanel mainpanel;
    private com.raven.datechooser.DateChooser startdate;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress3;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtemail3;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname3;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JTextField txtphone3;
    private javax.swing.JTextField txtpoint;
    private javax.swing.JTextField txtpoint1;
    private javax.swing.JTextField txtpoint3;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
