/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import DAL.TaiKhoanDAL;
import DTO.*;
import BLL.*;
/**
 *
 * @author THAONGAN
 */
public class DangNhap extends javax.swing.JFrame {
    /**
     * Creates new form DangNhap
     */
    public static DangNhap frmInstance;
    public String txt;
    public String txt1;
    public String taikhoan ;
    public DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        frmInstance = this;
        // iconURL is null when not found
        setTitle("Pharmacy Management System");
        setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\learn IT\\Java\\QuanLyNhaThuoc\\src\\images\\pharmacy icon.png"));
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invisible = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        btnpanel = new keeptoo.KGradientPanel();
        btnDangNhap = new javax.swing.JButton();
        btnpanelhover = new keeptoo.KGradientPanel();
        btnDangNhaphover = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1080, 671));
        setMinimumSize(new java.awt.Dimension(822, 671));
        setName("loginframe"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setAlignmentX(1.0F);
        jPanel1.setAlignmentY(1.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(2560, 1600));
        jPanel1.setMinimumSize(new java.awt.Dimension(822, 671));
        jPanel1.setPreferredSize(new java.awt.Dimension(822, 671));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(2560, 1600));
        jPanel3.setMinimumSize(new java.awt.Dimension(401, 671));
        jPanel3.setPreferredSize(new java.awt.Dimension(401, 671));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Nhập ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 31, 162, -1));

        txtTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTenTaiKhoan.setForeground(new java.awt.Color(102, 102, 102));
        txtTenTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        jPanel3.add(txtTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 270, 20));

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMatKhau.setToolTipText("");
        txtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        txtMatKhau.setName(""); // NOI18N
        jPanel3.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 270, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Tên đăng nhập");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 137, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Mật khẩu");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 123, -1));

        invisible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-invisible-25.png"))); // NOI18N
        invisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invisible.setPreferredSize(new java.awt.Dimension(40, 30));
        invisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invisibleMouseClicked(evt);
            }
        });
        jPanel3.add(invisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 37, -1));

        visible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-25.png"))); // NOI18N
        visible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visible.setPreferredSize(new java.awt.Dimension(40, 30));
        visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visibleMouseClicked(evt);
            }
        });
        jPanel3.add(visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 37, -1));

        btnpanel.setkEndColor(new java.awt.Color(85, 98, 112));
        btnpanel.setkGradientFocus(150);
        btnpanel.setkStartColor(new java.awt.Color(13, 131, 120));
        btnpanel.setOpaque(false);
        btnpanel.setPreferredSize(new java.awt.Dimension(100, 22));
        btnpanel.setRoundBottomLeft(20);
        btnpanel.setRoundBottomRight(20);
        btnpanel.setRoundTopLeft(20);
        btnpanel.setRoundTopRight(20);

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setToolTipText("");
        btnDangNhap.setBorder(null);
        btnDangNhap.setBorderPainted(false);
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDangNhap.setVerifyInputWhenFocusTarget(false);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnpanelLayout = new javax.swing.GroupLayout(btnpanel);
        btnpanel.setLayout(btnpanelLayout);
        btnpanelLayout.setHorizontalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnpanelLayout.setVerticalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(btnpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 170, 39));

        btnpanelhover.setkEndColor(new java.awt.Color(49, 255, 204));
        btnpanelhover.setkGradientFocus(150);
        btnpanelhover.setkStartColor(new java.awt.Color(120, 215, 255));
        btnpanelhover.setOpaque(false);
        btnpanelhover.setPreferredSize(new java.awt.Dimension(100, 22));
        btnpanelhover.setRoundBottomLeft(20);
        btnpanelhover.setRoundBottomRight(20);
        btnpanelhover.setRoundTopLeft(20);
        btnpanelhover.setRoundTopRight(20);

        btnDangNhaphover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDangNhaphover.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhaphover.setText("Đăng Nhập");
        btnDangNhaphover.setToolTipText("");
        btnDangNhaphover.setBorder(null);
        btnDangNhaphover.setBorderPainted(false);
        btnDangNhaphover.setContentAreaFilled(false);
        btnDangNhaphover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhaphover.setFocusPainted(false);
        btnDangNhaphover.setFocusable(false);
        btnDangNhaphover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhaphover.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDangNhaphover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhaphoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhaphoverMouseExited(evt);
            }
        });
        btnDangNhaphover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhaphoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnpanelhoverLayout = new javax.swing.GroupLayout(btnpanelhover);
        btnpanelhover.setLayout(btnpanelhoverLayout);
        btnpanelhoverLayout.setHorizontalGroup(
            btnpanelhoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnpanelhoverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDangNhaphover, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnpanelhoverLayout.setVerticalGroup(
            btnpanelhoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnpanelhoverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDangNhaphover, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(btnpanelhover, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 170, 39));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(480, 0, 410, 670);

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(480, 671));
        jPanel4.setPreferredSize(new java.awt.Dimension(421, 671));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pharmacy image-login.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 480, 671);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisibleMouseClicked
        // TODO add your handling code here:
        txtMatKhau.setEchoChar((char)0);
        invisible.setVisible(false);
        invisible.setEnabled(false);
        visible.setEnabled(true);
        visible.setEnabled(true);
    }//GEN-LAST:event_invisibleMouseClicked

    private void visibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleMouseClicked
        // TODO add your handling code here:
        txtMatKhau.setEchoChar((char)8226);
        invisible.setVisible(true);
        invisible.setEnabled(true);
        visible.setEnabled(false);
        visible.setEnabled(false);
    }//GEN-LAST:event_visibleMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        // TODO add your handling code here:
        btnpanel.setVisible(false);
        btnpanel.setEnabled(false);
        btnpanelhover.setVisible(true);
        btnpanelhover.setEnabled(true);
    }//GEN-LAST:event_btnDangNhapMouseEntered

    private void btnDangNhaphoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhaphoverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhaphoverMouseEntered

    private void btnDangNhaphoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhaphoverMouseExited
        // TODO add your handling code here:
        btnpanelhover.setVisible(false);
        btnpanelhover.setEnabled(false);
        btnpanel.setVisible(true);
        btnpanel.setEnabled(true);
    }//GEN-LAST:event_btnDangNhaphoverMouseExited

    private void btnDangNhaphoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhaphoverActionPerformed
        // TODO add your handling code here:
        TaiKhoanBLL TaiKhoanDangNhap = new TaiKhoanBLL();
        String tentk = txtTenTaiKhoan.getText();
        String mk = txtMatKhau.getText();
        TaiKhoan tk = TaiKhoanDangNhap.dangNhapBLL(tentk, mk);
               
        if (tk == null)
            JOptionPane.showMessageDialog(null, "Tên đăng nhập hoặc mật khẩu không đúng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
             txt = Integer.toString(tk.getMaNV()); 
             txt1 = Integer.toString(tk.getVaiTro()); 
             taikhoan=tentk;
            this.dispose();
            if (TaiKhoanDangNhap.GetVaiTro(tk) == 0)
            { 
                ManagerDashBoard ql = new ManagerDashBoard();
                ql.setVisible(true);
            } else {   
            EmpDashBoard e = new EmpDashBoard();
            e.setVisible(true);
            }
        }
            
    }//GEN-LAST:event_btnDangNhaphoverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DangNhap().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDangNhaphover;
    private keeptoo.KGradientPanel btnpanel;
    private keeptoo.KGradientPanel btnpanelhover;
    private javax.swing.JLabel invisible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JLabel visible;
    // End of variables declaration//GEN-END:variables
}
