package GUI;

import java.text.SimpleDateFormat;
import java.util.Date;
import BLL.*;
import DTO.*;
import Utils.DBUtils;
import java.util.ArrayList;
import java.sql.*;
import java.text.DateFormat;

public class EmpDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form EmpDashBoard
     */
    public EmpDashBoard() {
        initComponents();
        setLocationRelativeTo(null);
        HienThiNgay();
        HienThiThuoc();
        CapNhatThuoc();
    }
    ThuocBLL tbll=new ThuocBLL();
    KhoThuocBLL ktbll=new KhoThuocBLL();
        public void HienThiNgay(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = sdf.format(new Date());
        txtNgay.setText(date);
    }
        public void HienThiThuoc() {
        txtNgay1.setText(String.valueOf(tbll.LOadExpiry1_BLL()));
    }
    public void CapNhatThuoc() {
        ArrayList<Thuoc> thuocs = tbll.LoadExpiry2_BLL();//tìm thuốc đã hết hạn hoặc số lượng bằng 0
        Thuoc t = new Thuoc();
        KhoThuoc k = new KhoThuoc();
        for (int i = 0; i < thuocs.size(); i++) {
            t = thuocs.get(i);
            String MASP = t.getMASP();
            ArrayList<KhoThuoc> khoThuocs = ktbll.Search_BLL(MASP);
            if(khoThuocs.isEmpty()){
                
            }else{
                for (int j = 0; j < 1; j++) {
                k = khoThuocs.get(j);
                
                Date date = convertStringtoDate(k.getNGAYSX(), "yyyy-MM-dd");
                Date date1 = convertStringtoDate(k.getHSD(), "yyyy-MM-dd");
                String result = convertDatetoString(date, "dd-MM-yyyy");
                String result1 = convertDatetoString(date1, "dd-MM-yyyy");
                
                tbll.Update(MASP, t.getTENSP(), k.getDVT(), k.getGIA(), k.getSOLUONG(), k.getNHASX(), k.getSOLOSX(), result, result1, k.getGIAGOC(), k.getMANCC(),1);
                ktbll.Delete(MASP, t.getTENSP(), k.getDVT(), k.getGIA(), k.getSOLUONG(), k.getNHASX(), k.getSOLOSX(), result, result1, k.getGIAGOC(), k.getMANCC());

            }
            }
        }
    }
    public String convertDatetoString(Date date, String pattern) {
        DateFormat df = new SimpleDateFormat(pattern);
        return df.format(date);
    }

    public Date convertStringtoDate(String dateinString, String pattern) {
        DateFormat df = new SimpleDateFormat(pattern);
        Date startDate = null;
        try {
            startDate = df.parse(dateinString);
            String newDateString = df.format(startDate);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return startDate;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        GradientPaneltop = new keeptoo.KGradientPanel();
        lbTitle = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        medicineimg2 = new javax.swing.JLabel();
        cloudyimg = new javax.swing.JLabel();
        medicineimg1 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNgay1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnBaocao = new keeptoo.Mybutton();
        btnProfile = new keeptoo.Mybutton();
        jLabel14 = new javax.swing.JLabel();
        btnKH = new keeptoo.Mybutton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnThuoc = new keeptoo.Mybutton();
        btnHD = new keeptoo.Mybutton();
        jLabel18 = new javax.swing.JLabel();
        btnNhapThuoc = new keeptoo.Mybutton();
        jLabel17 = new javax.swing.JLabel();
        btnNCC = new keeptoo.Mybutton();
        jPanel4 = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        medicineimg3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnDangXuat = new keeptoo.Mybutton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 131, 149));
        setMinimumSize(new java.awt.Dimension(1100, 783));

        mainpanel.setBackground(new java.awt.Color(10, 77, 105));
        mainpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 15, 0, new java.awt.Color(8, 131, 149)));
        mainpanel.setForeground(new java.awt.Color(10, 77, 105));
        mainpanel.setMaximumSize(new java.awt.Dimension(1200, 750));
        mainpanel.setMinimumSize(new java.awt.Dimension(1101, 750));
        mainpanel.setPreferredSize(new java.awt.Dimension(1101, 750));
        mainpanel.setLayout(null);

        GradientPaneltop.setBackground(new java.awt.Color(10, 77, 105));
        GradientPaneltop.setkEndColor(new java.awt.Color(1, 255, 202));
        GradientPaneltop.setkGradientFocus(850);
        GradientPaneltop.setkStartColor(new java.awt.Color(9, 131, 149));
        GradientPaneltop.setRoundBottomLeft(50);
        GradientPaneltop.setRoundBottomRight(50);
        GradientPaneltop.setRoundTopLeft(50);
        GradientPaneltop.setRoundTopRight(50);

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 204));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("<html> HỆ THỐNG QUẢN LÝ NHÀ THUỐC <html>");

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDate.setForeground(new java.awt.Color(255, 255, 255));
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDate.setText("Ngày");

        medicineimg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (6).png"))); // NOI18N

        cloudyimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cloudyimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloudy.png"))); // NOI18N
        cloudyimg.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        medicineimg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        medicineimg1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medicineimg1.setAlignmentY(0.0F);

        txtNgay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNgay.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lượng thuốc sắp hết hạn");

        txtNgay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNgay1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout GradientPaneltopLayout = new javax.swing.GroupLayout(GradientPaneltop);
        GradientPaneltop.setLayout(GradientPaneltopLayout);
        GradientPaneltopLayout.setHorizontalGroup(
            GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicineimg2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(medicineimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cloudyimg, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );
        GradientPaneltopLayout.setVerticalGroup(
            GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GradientPaneltopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cloudyimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicineimg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(medicineimg2))
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        mainpanel.add(GradientPaneltop);
        GradientPaneltop.setBounds(40, 40, 740, 120);

        jPanel1.setBackground(new java.awt.Color(9, 131, 149));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(4, 191, 219)));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 65));
        jPanel1.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine1 (4).png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(141, 12, 41, 41);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(38, 12, 41, 41);

        mainpanel.add(jPanel1);
        jPanel1.setBounds(30, 190, 210, 60);

        jPanel2.setBackground(new java.awt.Color(9, 131, 149));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(4, 191, 219)));
        jPanel2.setMinimumSize(new java.awt.Dimension(270, 65));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 65));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (4).png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel3)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        mainpanel.add(jPanel2);
        jPanel2.setBounds(270, 190, 260, 60);

        jPanel3.setBackground(new java.awt.Color(9, 131, 149));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(4, 191, 219)));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 65));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 65));
        jPanel3.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine1 (4).png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(42, 12, 41, 41);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(144, 12, 41, 41);

        mainpanel.add(jPanel3);
        jPanel3.setBounds(560, 190, 230, 60);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(4, 191, 219)));
        kGradientPanel1.setkEndColor(new java.awt.Color(8, 131, 149));
        kGradientPanel1.setkGradientFocus(550);
        kGradientPanel1.setkStartColor(new java.awt.Color(10, 77, 105));
        kGradientPanel1.setLayout(null);

        kGradientPanel2.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel2.setkGradientFocus(650);
        kGradientPanel2.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(748, 112));
        kGradientPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        kGradientPanel2.add(jLabel8);
        jLabel8.setBounds(10, 20, 60, 60);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        kGradientPanel2.add(jLabel15);
        jLabel15.setBounds(400, 20, 60, 60);

        btnBaocao.setBorder(null);
        btnBaocao.setText("       Báo cáo");
        btnBaocao.setBorderPainted(false);
        btnBaocao.setColor1(new java.awt.Color(216, 171, 255));
        btnBaocao.setColor2(new java.awt.Color(3, 137, 255));
        btnBaocao.setFocusable(false);
        btnBaocao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBaocao.setkGradientFocus(225);
        btnBaocao.setPreferredSize(new java.awt.Dimension(170, 65));
        btnBaocao.setRadius(40);
        btnBaocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaocaoActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnBaocao);
        btnBaocao.setBounds(30, 20, 120, 65);

        btnProfile.setBorder(null);
        btnProfile.setText("   Hồ sơ");
        btnProfile.setBorderPainted(false);
        btnProfile.setColor1(new java.awt.Color(216, 171, 255));
        btnProfile.setColor2(new java.awt.Color(3, 137, 255));
        btnProfile.setFocusable(false);
        btnProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProfile.setkGradientFocus(225);
        btnProfile.setPreferredSize(new java.awt.Dimension(170, 65));
        btnProfile.setRadius(40);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnProfile);
        btnProfile.setBounds(420, 20, 120, 65);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rating.png"))); // NOI18N
        kGradientPanel2.add(jLabel14);
        jLabel14.setBounds(190, 20, 70, 60);

        btnKH.setBorder(null);
        btnKH.setText("    Khách hàng");
        btnKH.setBorderPainted(false);
        btnKH.setColor1(new java.awt.Color(216, 171, 255));
        btnKH.setColor2(new java.awt.Color(3, 137, 255));
        btnKH.setFocusable(false);
        btnKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKH.setkGradientFocus(225);
        btnKH.setPreferredSize(new java.awt.Dimension(170, 65));
        btnKH.setRadius(40);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnKH);
        btnKH.setBounds(230, 20, 120, 65);

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(6, 197, 748, 112);

        kGradientPanel3.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel3.setkGradientFocus(650);
        kGradientPanel3.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel3.setLayout(null);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pills.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel3.add(jLabel9);
        jLabel9.setBounds(20, 20, 60, 60);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        kGradientPanel3.add(jLabel12);
        jLabel12.setBounds(190, 20, 60, 60);

        btnThuoc.setBorder(null);
        btnThuoc.setText("   Thuốc");
        btnThuoc.setBorderPainted(false);
        btnThuoc.setColor1(new java.awt.Color(216, 171, 255));
        btnThuoc.setColor2(new java.awt.Color(3, 137, 255));
        btnThuoc.setFocusable(false);
        btnThuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThuoc.setkGradientFocus(225);
        btnThuoc.setPreferredSize(new java.awt.Dimension(170, 65));
        btnThuoc.setRadius(40);
        btnThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuocActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnThuoc);
        btnThuoc.setBounds(40, 20, 120, 65);

        btnHD.setBorder(null);
        btnHD.setText("Hóa đơn");
        btnHD.setBorderPainted(false);
        btnHD.setColor1(new java.awt.Color(216, 171, 255));
        btnHD.setColor2(new java.awt.Color(3, 137, 255));
        btnHD.setFocusable(false);
        btnHD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHD.setkGradientFocus(225);
        btnHD.setPreferredSize(new java.awt.Dimension(170, 65));
        btnHD.setRadius(40);
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnHD);
        btnHD.setBounds(230, 20, 120, 65);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-inventory-60.png"))); // NOI18N
        kGradientPanel3.add(jLabel18);
        jLabel18.setBounds(380, 20, 60, 60);

        btnNhapThuoc.setBorder(null);
        btnNhapThuoc.setText("    Nhập thuốc");
        btnNhapThuoc.setBorderPainted(false);
        btnNhapThuoc.setColor1(new java.awt.Color(216, 171, 255));
        btnNhapThuoc.setColor2(new java.awt.Color(3, 137, 255));
        btnNhapThuoc.setFocusable(false);
        btnNhapThuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapThuoc.setkGradientFocus(225);
        btnNhapThuoc.setPreferredSize(new java.awt.Dimension(170, 65));
        btnNhapThuoc.setRadius(40);
        btnNhapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapThuocActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnNhapThuoc);
        btnNhapThuoc.setBounds(410, 20, 130, 65);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-supplier-60.png"))); // NOI18N
        jLabel17.setToolTipText("");
        kGradientPanel3.add(jLabel17);
        jLabel17.setBounds(560, 20, 60, 60);

        btnNCC.setBorder(null);
        btnNCC.setText("     Nhà cung cấp");
        btnNCC.setBorderPainted(false);
        btnNCC.setColor1(new java.awt.Color(216, 171, 255));
        btnNCC.setColor2(new java.awt.Color(3, 137, 255));
        btnNCC.setFocusable(false);
        btnNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNCC.setkGradientFocus(225);
        btnNCC.setPreferredSize(new java.awt.Dimension(170, 65));
        btnNCC.setRadius(40);
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnNCC);
        btnNCC.setBounds(590, 20, 140, 65);

        kGradientPanel1.add(kGradientPanel3);
        kGradientPanel3.setBounds(6, 42, 748, 112);

        mainpanel.add(kGradientPanel1);
        kGradientPanel1.setBounds(30, 280, 760, 350);

        jPanel4.setBackground(new java.awt.Color(5, 191, 219));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(8, 131, 149)));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setPreferredSize(new java.awt.Dimension(780, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        mainpanel.add(jPanel4);
        jPanel4.setBounds(0, 680, 810, 20);

        kGradientPanel4.setBackground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setForeground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel4.setkGradientFocus(50);
        kGradientPanel4.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setMinimumSize(new java.awt.Dimension(20, 690));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(20, 690));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        mainpanel.add(kGradientPanel4);
        kGradientPanel4.setBounds(810, 0, 20, 710);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        mainpanel.add(jLabel2);
        jLabel2.setBounds(140, 640, 41, 41);

        medicineimg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (6).png"))); // NOI18N
        mainpanel.add(medicineimg3);
        medicineimg3.setBounds(650, 640, 41, 41);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        mainpanel.add(jLabel7);
        jLabel7.setBounds(880, 50, 171, 120);

        kGradientPanel5.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel5.setkGradientFocus(175);
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("TRANG CHỦ");
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label.setInheritsPopupMenu(false);

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainpanel.add(kGradientPanel5);
        kGradientPanel5.setBounds(830, 200, 250, 70);

        jPanel5.setBackground(new java.awt.Color(8, 131, 149));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        mainpanel.add(jPanel5);
        jPanel5.setBounds(-10, 430, 40, 50);

        jPanel6.setBackground(new java.awt.Color(8, 131, 149));
        jPanel6.setPreferredSize(new java.awt.Dimension(290, 95));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(jPanel6);
        jPanel6.setBounds(790, 325, 290, 110);

        jPanel7.setBackground(new java.awt.Color(8, 131, 149));
        jPanel7.setPreferredSize(new java.awt.Dimension(290, 95));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(jPanel7);
        jPanel7.setBounds(790, 480, 290, 110);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        mainpanel.add(jLabel16);
        jLabel16.setBounds(863, 618, 50, 50);

        btnDangXuat.setBorder(null);
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.setColor1(new java.awt.Color(216, 171, 255));
        btnDangXuat.setColor2(new java.awt.Color(3, 137, 255));
        btnDangXuat.setFocusable(false);
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat.setkGradientFocus(225);
        btnDangXuat.setPreferredSize(new java.awt.Dimension(170, 65));
        btnDangXuat.setRadius(40);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        mainpanel.add(btnDangXuat);
        btnDangXuat.setBounds(890, 620, 130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Profile p = new Profile();
        p.setVisible(true);        
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        // TODO add your handling code here:
        this.dispose();
        QLBanHang s = new QLBanHang();
        s.setVisible(true);
    }//GEN-LAST:event_btnHDActionPerformed

    private void btnThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Medicine m = new Medicine();
        m.setVisible(true);
    }//GEN-LAST:event_btnThuocActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        // TODO add your handling code here:
        this.dispose();
        QLNhaCungCap m = new QLNhaCungCap();
        m.setVisible(true);
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btnNhapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapThuocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        QLNhapHang m = new QLNhapHang();
        m.setVisible(true);
    }//GEN-LAST:event_btnNhapThuocActionPerformed

    private void btnBaocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaocaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RevenueStatistics m = new RevenueStatistics();
        m.setVisible(true);
    }//GEN-LAST:event_btnBaocaoActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Customer m =new Customer();
        m.setVisible(true);
    }//GEN-LAST:event_btnKHActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel GradientPaneltop;
    private keeptoo.Mybutton btnBaocao;
    private keeptoo.Mybutton btnDangXuat;
    private keeptoo.Mybutton btnHD;
    private keeptoo.Mybutton btnKH;
    private keeptoo.Mybutton btnNCC;
    private keeptoo.Mybutton btnNhapThuoc;
    private keeptoo.Mybutton btnProfile;
    private keeptoo.Mybutton btnThuoc;
    private javax.swing.JLabel cloudyimg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel medicineimg1;
    private javax.swing.JLabel medicineimg2;
    private javax.swing.JLabel medicineimg3;
    private javax.swing.JLabel txtNgay;
    private javax.swing.JLabel txtNgay1;
    // End of variables declaration//GEN-END:variables
}
