package GUI;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import BLL.*;
import DTO.*;
import Utils.DBUtils;
import java.util.ArrayList;
import java.sql.*;
import java.text.DateFormat;
import javax.swing.JLabel;
import java.util.*;
import javax.swing.JOptionPane;

public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form EmpDashBoard
     */
    public Profile() {
        initComponents();
        setLocationRelativeTo(null);
        HienThiNgay();
        labelMaNV.setText(DangNhap.frmInstance.txt);
        HienThiThongTin(ebll.Search_BLL(labelMaNV.getText()));

    }
    private String VAITRO = DangNhap.frmInstance.txt1;
    NhanVienBLL ebll = new NhanVienBLL();

    public void HienThiNgay() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = sdf.format(new Date());
        Date.setText(date);
    }

    public void HienThiThongTin(ArrayList<NhanVien> dsnhanvien) {
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatter1 = new SimpleDateFormat("d-M-yyyy");
            NhanVien t = new NhanVien();
            for (int i = 0; i < dsnhanvien.size(); i++) {
                t = dsnhanvien.get(i);
                String HOTEN = t.getHoten();
                String GIOITINH = t.getGioitinh();
                String NGAYSINH = t.getNgaysinh();
                String EMAIL = t.getEmail();
                String SODT = t.getSdt();
                String NGAYVAOLAM = t.getNgayvaolam();
                String DIACHI = t.getDiachi();
                              
                Date date=convertStringtoDate(NGAYSINH, "yyyy-MM-dd");
                Date date1=convertStringtoDate(NGAYVAOLAM, "yyyy-MM-dd");
                String result =convertDatetoString(date, "dd-MM-yyyy");
                String result1 =convertDatetoString(date1, "dd-MM-yyyy");
                
                txtName.setText(HOTEN);
                comboboxGender.setSelectedItem(GIOITINH);
                txtDateofBirth.setText(result);
                txtEmail.setText(EMAIL);
                txtSDT.setText(SODT);
                txtNgayVaoLam.setText(result1);
                txtDiaChi.setText(DIACHI);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public String convertDatetoString(Date date, String pattern){
        DateFormat df= new SimpleDateFormat(pattern);
        return df.format(date);
    }
    public Date convertStringtoDate(String dateinString, String pattern){
        DateFormat df= new SimpleDateFormat(pattern);
        Date startDate=null;
        try {
            startDate=df.parse(dateinString);
            String newDateString= df.format(startDate);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return startDate;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateofbirth = new com.raven.datechooser.DateChooser();
        startdate = new com.raven.datechooser.DateChooser();
        mainpanel = new javax.swing.JPanel();
        GradientPaneltop = new keeptoo.KGradientPanel();
        lbDate = new javax.swing.JLabel();
        cloudyimg = new javax.swing.JLabel();
        lbDate1 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        labelMaNV = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        txtName = new javax.swing.JTextField();
        lbDate3 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lbDate5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        txtDateofBirth = new javax.swing.JTextField();
        calendarchoose = new javax.swing.JButton();
        lbDate2 = new javax.swing.JLabel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        lbDate7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbDate4 = new javax.swing.JLabel();
        lbDate6 = new javax.swing.JLabel();
        lbDate8 = new javax.swing.JLabel();
        comboboxGender = new javax.swing.JComboBox<>();
        txtNgayVaoLam = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        choosedate = new javax.swing.JButton();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new keeptoo.Mybutton();
        panelSave = new keeptoo.KGradientPanel();
        btnSave = new javax.swing.JButton();
        panelSavehover = new keeptoo.KGradientPanel();
        btnCapNhat = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelSavehover1 = new keeptoo.KGradientPanel();
        btnCapNhat1 = new javax.swing.JButton();
        panelSave1 = new keeptoo.KGradientPanel();
        btnSave1 = new javax.swing.JButton();

        dateofbirth.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dateofbirth.setTextRefernce(txtDateofBirth);

        startdate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        startdate.setTextRefernce(txtNgayVaoLam);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 131, 149));
        setMinimumSize(new java.awt.Dimension(1100, 783));

        mainpanel.setBackground(new java.awt.Color(10, 77, 105));
        mainpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 15, 0, new java.awt.Color(8, 131, 149)));
        mainpanel.setForeground(new java.awt.Color(10, 77, 105));
        mainpanel.setMaximumSize(new java.awt.Dimension(1200, 750));
        mainpanel.setMinimumSize(new java.awt.Dimension(1101, 750));
        mainpanel.setPreferredSize(new java.awt.Dimension(1101, 750));
        mainpanel.setLayout(null);

        GradientPaneltop.setBackground(new java.awt.Color(10, 77, 105));
        GradientPaneltop.setkEndColor(new java.awt.Color(1, 255, 202));
        GradientPaneltop.setkGradientFocus(850);
        GradientPaneltop.setkStartColor(new java.awt.Color(9, 131, 149));
        GradientPaneltop.setRoundBottomLeft(70);
        GradientPaneltop.setRoundBottomRight(70);
        GradientPaneltop.setRoundTopLeft(70);
        GradientPaneltop.setRoundTopRight(70);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDate.setForeground(new java.awt.Color(255, 255, 255));
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate.setText("Ngày");

        cloudyimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cloudyimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloudy.png"))); // NOI18N
        cloudyimg.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbDate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDate1.setForeground(new java.awt.Color(255, 255, 255));
        lbDate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate1.setText("ID");
        lbDate1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Date.setEditable(false);
        Date.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        labelMaNV.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        labelMaNV.setForeground(new java.awt.Color(255, 255, 255));
        labelMaNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GradientPaneltopLayout = new javax.swing.GroupLayout(GradientPaneltop);
        GradientPaneltop.setLayout(GradientPaneltopLayout);
        GradientPaneltopLayout.setHorizontalGroup(
            GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(110, 110, 110))
                    .addGroup(GradientPaneltopLayout.createSequentialGroup()
                        .addComponent(labelMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(cloudyimg, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        GradientPaneltopLayout.setVerticalGroup(
            GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GradientPaneltopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDate1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(GradientPaneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(GradientPaneltopLayout.createSequentialGroup()
                .addComponent(cloudyimg)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainpanel.add(GradientPaneltop);
        GradientPaneltop.setBounds(60, 40, 720, 100);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(4, 191, 219)));
        kGradientPanel1.setkEndColor(new java.awt.Color(8, 131, 149));
        kGradientPanel1.setkGradientFocus(550);
        kGradientPanel1.setkStartColor(new java.awt.Color(10, 77, 105));
        kGradientPanel1.setLayout(null);

        kGradientPanel2.setkEndColor(new java.awt.Color(1, 255, 202));
        kGradientPanel2.setkGradientFocus(750);
        kGradientPanel2.setkStartColor(new java.awt.Color(9, 131, 149));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lbDate3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate3.setForeground(new java.awt.Color(255, 255, 255));
        lbDate3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate3.setText("Họ và tên");
        lbDate3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lbDate3)
                .addGap(63, 63, 63)
                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(209, 209, 209))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(6, 6, 728, 60);

        kGradientPanel3.setkEndColor(new java.awt.Color(1, 255, 202));
        kGradientPanel3.setkGradientFocus(750);
        kGradientPanel3.setkStartColor(new java.awt.Color(9, 131, 149));

        lbDate5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate5.setForeground(new java.awt.Color(255, 255, 255));
        lbDate5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate5.setText("SĐT");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lbDate5)
                .addGap(106, 106, 106)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        kGradientPanel1.add(kGradientPanel3);
        kGradientPanel3.setBounds(6, 250, 728, 60);

        kGradientPanel6.setkEndColor(new java.awt.Color(1, 255, 202));
        kGradientPanel6.setkGradientFocus(750);
        kGradientPanel6.setkStartColor(new java.awt.Color(9, 131, 149));

        txtDateofBirth.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        calendarchoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-24.png"))); // NOI18N
        calendarchoose.setBorderPainted(false);
        calendarchoose.setContentAreaFilled(false);
        calendarchoose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calendarchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarchooseActionPerformed(evt);
            }
        });

        lbDate2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate2.setForeground(new java.awt.Color(255, 255, 255));
        lbDate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate2.setText("Ngày sinh");
        lbDate2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lbDate2)
                .addGap(60, 60, 60)
                .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarchoose)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDate2)
                        .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        kGradientPanel1.add(kGradientPanel6);
        kGradientPanel6.setBounds(6, 129, 728, 60);

        kGradientPanel7.setkEndColor(new java.awt.Color(1, 255, 202));
        kGradientPanel7.setkGradientFocus(750);
        kGradientPanel7.setkStartColor(new java.awt.Color(9, 131, 149));

        lbDate7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate7.setForeground(new java.awt.Color(255, 255, 255));
        lbDate7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate7.setText("Địa chỉ");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(lbDate7)
                .addGap(82, 82, 82)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        kGradientPanel1.add(kGradientPanel7);
        kGradientPanel7.setBounds(6, 364, 728, 60);

        lbDate4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate4.setForeground(new java.awt.Color(255, 255, 255));
        lbDate4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate4.setText("Giới tính");
        lbDate4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(lbDate4);
        lbDate4.setBounds(178, 90, 68, 20);

        lbDate6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate6.setForeground(new java.awt.Color(255, 255, 255));
        lbDate6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate6.setText("Email");
        kGradientPanel1.add(lbDate6);
        lbDate6.setBounds(178, 210, 44, 20);

        lbDate8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDate8.setForeground(new java.awt.Color(255, 255, 255));
        lbDate8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate8.setText("Ngày vào làm");
        kGradientPanel1.add(lbDate8);
        lbDate8.setBounds(178, 330, 110, 20);

        comboboxGender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboboxGender.setMaximumRowCount(2);
        comboboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ ", "Nam" }));
        comboboxGender.setBorder(null);
        comboboxGender.setFocusable(false);
        kGradientPanel1.add(comboboxGender);
        comboboxGender.setBounds(316, 90, 72, 23);

        txtNgayVaoLam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kGradientPanel1.add(txtNgayVaoLam);
        txtNgayVaoLam.setBounds(317, 325, 100, 25);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kGradientPanel1.add(txtEmail);
        txtEmail.setBounds(316, 209, 194, 25);

        choosedate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-24.png"))); // NOI18N
        choosedate.setBorderPainted(false);
        choosedate.setContentAreaFilled(false);
        choosedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosedateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(choosedate);
        choosedate.setBounds(420, 325, 40, 31);

        mainpanel.add(kGradientPanel1);
        kGradientPanel1.setBounds(50, 180, 740, 430);

        kGradientPanel4.setBackground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setForeground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel4.setkGradientFocus(50);
        kGradientPanel4.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setMinimumSize(new java.awt.Dimension(20, 690));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(20, 690));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        mainpanel.add(kGradientPanel4);
        kGradientPanel4.setBounds(810, 0, 20, 710);

        kGradientPanel5.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel5.setkGradientFocus(175);
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Profile");
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label.setInheritsPopupMenu(false);

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainpanel.add(kGradientPanel5);
        kGradientPanel5.setBounds(830, 180, 250, 70);

        jPanel5.setBackground(new java.awt.Color(8, 131, 149));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mainpanel.add(jPanel5);
        jPanel5.setBounds(-10, 490, 60, 30);

        jPanel6.setBackground(new java.awt.Color(8, 131, 149));
        jPanel6.setPreferredSize(new java.awt.Dimension(290, 95));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mainpanel.add(jPanel6);
        jPanel6.setBounds(830, 305, 250, 240);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow.png"))); // NOI18N
        mainpanel.add(jLabel9);
        jLabel9.setBounds(890, 622, 45, 45);

        btnBack.setBorder(null);
        btnBack.setText("      Quay lại");
        btnBack.setColor1(new java.awt.Color(216, 171, 255));
        btnBack.setColor2(new java.awt.Color(3, 137, 255));
        btnBack.setFocusable(false);
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setkGradientFocus(225);
        btnBack.setPreferredSize(new java.awt.Dimension(170, 65));
        btnBack.setRadius(39);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainpanel.add(btnBack);
        btnBack.setBounds(890, 620, 130, 50);

        panelSave.setkEndColor(new java.awt.Color(105, 190, 255));
        panelSave.setkGradientFocus(100);
        panelSave.setkStartColor(new java.awt.Color(88, 255, 250));
        panelSave.setOpaque(false);
        panelSave.setRoundBottomLeft(15);
        panelSave.setRoundBottomRight(15);
        panelSave.setRoundTopLeft(15);
        panelSave.setRoundTopRight(15);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Cập nhật");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelSaveLayout = new javax.swing.GroupLayout(panelSave);
        panelSave.setLayout(panelSaveLayout);
        panelSaveLayout.setHorizontalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelSaveLayout.setVerticalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpanel.add(panelSave);
        panelSave.setBounds(240, 630, 140, 30);

        panelSavehover.setkEndColor(new java.awt.Color(49, 255, 204));
        panelSavehover.setkGradientFocus(100);
        panelSavehover.setkStartColor(new java.awt.Color(120, 215, 255));
        panelSavehover.setOpaque(false);
        panelSavehover.setRoundBottomLeft(15);
        panelSavehover.setRoundBottomRight(15);
        panelSavehover.setRoundTopLeft(15);
        panelSavehover.setRoundTopRight(15);

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(null);
        btnCapNhat.setBorderPainted(false);
        btnCapNhat.setContentAreaFilled(false);
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseExited(evt);
            }
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSavehoverLayout = new javax.swing.GroupLayout(panelSavehover);
        panelSavehover.setLayout(panelSavehoverLayout);
        panelSavehoverLayout.setHorizontalGroup(
            panelSavehoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelSavehoverLayout.setVerticalGroup(
            panelSavehoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSavehoverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpanel.add(panelSavehover);
        panelSavehover.setBounds(240, 630, 140, 30);

        jPanel8.setBackground(new java.awt.Color(8, 131, 149));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mainpanel.add(jPanel8);
        jPanel8.setBounds(-10, 310, 60, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (6).png"))); // NOI18N
        mainpanel.add(jLabel1);
        jLabel1.setBounds(4, 270, 41, 41);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (5).png"))); // NOI18N
        mainpanel.add(jLabel2);
        jLabel2.setBounds(8, 450, 41, 41);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        mainpanel.add(jLabel3);
        jLabel3.setBounds(941, 265, 41, 41);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        mainpanel.add(jLabel4);
        jLabel4.setBounds(860, 265, 41, 41);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (5).png"))); // NOI18N
        mainpanel.add(jLabel5);
        jLabel5.setBounds(1020, 265, 41, 41);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        mainpanel.add(jLabel6);
        jLabel6.setBounds(890, 30, 130, 130);

        panelSavehover1.setkEndColor(new java.awt.Color(49, 255, 204));
        panelSavehover1.setkGradientFocus(100);
        panelSavehover1.setkStartColor(new java.awt.Color(120, 215, 255));
        panelSavehover1.setOpaque(false);
        panelSavehover1.setRoundBottomLeft(15);
        panelSavehover1.setRoundBottomRight(15);
        panelSavehover1.setRoundTopLeft(15);
        panelSavehover1.setRoundTopRight(15);

        btnCapNhat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapNhat1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat1.setText("Đổi mật khẩu");
        btnCapNhat1.setBorder(null);
        btnCapNhat1.setBorderPainted(false);
        btnCapNhat1.setContentAreaFilled(false);
        btnCapNhat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat1.setFocusable(false);
        btnCapNhat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhat1MouseExited(evt);
            }
        });
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSavehover1Layout = new javax.swing.GroupLayout(panelSavehover1);
        panelSavehover1.setLayout(panelSavehover1Layout);
        panelSavehover1Layout.setHorizontalGroup(
            panelSavehover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(panelSavehover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSavehover1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnCapNhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelSavehover1Layout.setVerticalGroup(
            panelSavehover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panelSavehover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSavehover1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnCapNhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainpanel.add(panelSavehover1);
        panelSavehover1.setBounds(490, 630, 140, 30);

        panelSave1.setkEndColor(new java.awt.Color(105, 190, 255));
        panelSave1.setkGradientFocus(100);
        panelSave1.setkStartColor(new java.awt.Color(88, 255, 250));
        panelSave1.setOpaque(false);
        panelSave1.setRoundBottomLeft(15);
        panelSave1.setRoundBottomRight(15);
        panelSave1.setRoundTopLeft(15);
        panelSave1.setRoundTopRight(15);

        btnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(255, 255, 255));
        btnSave1.setText("Đổi mật khẩu");
        btnSave1.setBorder(null);
        btnSave1.setBorderPainted(false);
        btnSave1.setContentAreaFilled(false);
        btnSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSave1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelSave1Layout = new javax.swing.GroupLayout(panelSave1);
        panelSave1.setLayout(panelSave1Layout);
        panelSave1Layout.setHorizontalGroup(
            panelSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSave1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSave1Layout.setVerticalGroup(
            panelSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSave1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpanel.add(panelSave1);
        panelSave1.setBounds(490, 630, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarchooseActionPerformed
        // TODO add your handling code here:
        dateofbirth.showPopup();
    }//GEN-LAST:event_calendarchooseActionPerformed

    private void choosedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosedateActionPerformed
        // TODO add your handling code here:
        startdate.showPopup();
    }//GEN-LAST:event_choosedateActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        // TODO add your handling code here:
        panelSave.setVisible(false);
        panelSave.setEnabled(false);
        panelSavehover.setVisible(true);
        panelSavehover.setEnabled(true);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnCapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseExited
        // TODO add your handling code here:
        panelSavehover.setVisible(false);
        panelSavehover.setEnabled(false);
        panelSave.setVisible(true);
        panelSave.setEnabled(true);
    }//GEN-LAST:event_btnCapNhatMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (VAITRO.equals("0")) {
            this.dispose();
            ManagerDashBoard m = new ManagerDashBoard();
            m.setVisible(true);
        } else if (VAITRO.equals("1")) {
            this.dispose();
            EmpDashBoard m = new EmpDashBoard();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        try {
            if (txtName.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên nhân viên không được bỏ trống");
            } else if (comboboxGender.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Giới tính không được bỏ trống");
            } else if (txtDateofBirth.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ngày sinh không được bỏ trống");
            } else if (txtEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Email không được bỏ trống");
            } else if (txtSDT.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không được bỏ trống");
            } else if (txtNgayVaoLam.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ngày bắt đầu làm không được bỏ trống");
            } else if (txtDiaChi.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Địa chỉ không được bỏ trống");
            } else {

                boolean check = ebll.Update(labelMaNV.getText(), txtName.getText(), String.valueOf(comboboxGender.getSelectedItem()), txtDateofBirth.getText(), txtEmail.getText(), txtSDT.getText(), txtNgayVaoLam.getText(), txtDiaChi.getText(),1);
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnCapNhat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhat1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhat1MouseExited

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed
        // TODO add your handling code here:
        QMK m =new QMK();
        m.setVisible(true);
        
    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void btnSave1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1MouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Profile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private keeptoo.KGradientPanel GradientPaneltop;
    private keeptoo.Mybutton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhat1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton calendarchoose;
    private javax.swing.JButton choosedate;
    private javax.swing.JLabel cloudyimg;
    private javax.swing.JComboBox<String> comboboxGender;
    private com.raven.datechooser.DateChooser dateofbirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel label;
    public javax.swing.JLabel labelMaNV;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDate1;
    private javax.swing.JLabel lbDate2;
    private javax.swing.JLabel lbDate3;
    private javax.swing.JLabel lbDate4;
    private javax.swing.JLabel lbDate5;
    private javax.swing.JLabel lbDate6;
    private javax.swing.JLabel lbDate7;
    private javax.swing.JLabel lbDate8;
    private javax.swing.JPanel mainpanel;
    private keeptoo.KGradientPanel panelSave;
    private keeptoo.KGradientPanel panelSave1;
    private keeptoo.KGradientPanel panelSavehover;
    private keeptoo.KGradientPanel panelSavehover1;
    private com.raven.datechooser.DateChooser startdate;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
