/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Utils.*;
import GUI.*;
import java.sql.*;
import javax.swing.JOptionPane;
public class QMK extends javax.swing.JFrame {

    /**
     * Creates new form QMK
     */
    public QMK() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private String TenTK= DangNhap.frmInstance.taikhoan;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMK = new javax.swing.JLabel();
        lbTenTK = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        lbMK1 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        labelQMK = new javax.swing.JLabel();
        currentpassword = new javax.swing.JPasswordField();
        mybutton21 = new keeptoo.Mybutton2();
        lbImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 426));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(410, 426));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 626));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbMK.setForeground(new java.awt.Color(0, 51, 204));
        lbMK.setText("Mật khẩu mới");
        jPanel1.add(lbMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, -1));

        lbTenTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbTenTK.setForeground(new java.awt.Color(0, 51, 204));
        lbTenTK.setText("Mật khẩu hiện tại");
        jPanel1.add(lbTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        newpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        newpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        newpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        newpassword.setCaretColor(new java.awt.Color(38, 117, 191));
        newpassword.setSelectionColor(new java.awt.Color(0, 153, 255));
        jPanel1.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 300, 30));

        lbMK1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbMK1.setForeground(new java.awt.Color(0, 51, 204));
        lbMK1.setText("Xác nhận mật khẩu");
        jPanel1.add(lbMK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, -1));

        confirmpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        confirmpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        confirmpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        confirmpassword.setCaretColor(new java.awt.Color(38, 117, 191));
        confirmpassword.setSelectionColor(new java.awt.Color(0, 153, 255));
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 300, 30));

        labelQMK.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelQMK.setText("Đổi mật khẩu");
        jPanel1.add(labelQMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 180, 30));
        jPanel1.add(currentpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 30));

        mybutton21.setBorder(null);
        mybutton21.setText("Lưu");
        mybutton21.setFocusable(false);
        mybutton21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mybutton21.setRadius(35);
        mybutton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mybutton21ActionPerformed(evt);
            }
        });
        jPanel1.add(mybutton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 320, 130, 40));

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QMK.jpg"))); // NOI18N
        lbImage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbImage.setMinimumSize(new java.awt.Dimension(410, 626));
        lbImage.setPreferredSize(new java.awt.Dimension(410, 626));
        jPanel1.add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mybutton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mybutton21ActionPerformed
        // TODO add your handling code here:
        String sql ="update TAIKHOAN set MATKHAU=? where MATKHAU=? and TENTK=?";
        Connection conn =new DBUtils().createConn();
        try {
            if(newpassword.getText().equals(confirmpassword.getText())){
                PreparedStatement pres = conn.prepareStatement(sql);
                pres.setString(1, confirmpassword.getText());
                pres.setString(2, currentpassword.getText());
                pres.setString(3, TenTK);
                pres.executeUpdate();
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
            }else{
                JOptionPane.showMessageDialog(null, "Mật khẩu mới và mật khẩu xác nhận phải trùng khớp");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_mybutton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JPasswordField currentpassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelQMK;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbMK;
    private javax.swing.JLabel lbMK1;
    private javax.swing.JLabel lbTenTK;
    private keeptoo.Mybutton2 mybutton21;
    private javax.swing.JPasswordField newpassword;
    // End of variables declaration//GEN-END:variables
}
