package GUI;

import Utils.DBUtils;
import com.raven.chart.ModelChart;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.beans.Statement;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleRole;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttribute;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class RevenueStatistics extends javax.swing.JFrame {

    /**
     * Creates new form EmpDashBoard
     */
    public RevenueStatistics() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(250, 250, 250));
        chart1.addLegend("Doanh thu", new Color(245, 189, 135));
        chart1.addLegend("Chi phí", new Color(0, 205, 0));
        chart2.addLegend("Hóa đơn bán", new Color(135, 189, 245));
        chart2.addLegend("Hóa đơn nhập", new Color(255, 215, 0));
        setVisible(true);

    }
    private String VAITRO = DangNhap.frmInstance.txt1;

    public void PrintRevenue() {
        MessageFormat header =new MessageFormat("Báo cáo thống kê");
        MessageFormat footer =new MessageFormat("----------------");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header,footer, true, set, true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Loaddata(String year) {
        DefaultTableModel tblModel = new DefaultTableModel();
        String sql = """
                     select sum(h.TRIGIA), count(distinct h.SOHD),sum(c.soluong) from HOADON h, CTHD c
                     where extract(year from NGHD)= ? and extract(month from NGHD)= ? and h.sohd=c.sohd""";
        String sql1 = """
                     select sum(h.TRIGIA), count(distinct h.SOHDN),sum(c.soluong) from HOADONNHAP h, CTHDNHAP c
                     where extract(year from NGHDN)= ? and extract(month from NGHDN)= ? and h.SOHDN=c.SOHDN""";
        String title[] = {"Tháng", "Năm", "Số hóa đơn xuất", "Số hóa đơn nhập", "Số thuốc bán","Số thuốc nhập", "Doanh thu","Chi phí"};
        tblModel.setColumnIdentifiers(title);
        try {
            Connection conn = new DBUtils().createConn();
            PreparedStatement pres = conn.prepareStatement(sql);
            PreparedStatement pres1 = conn.prepareStatement(sql1);
            int month = 1;
            while (month <= 12) {
                pres.setString(1, year);
                pres1.setString(1, year);
                String s = String.valueOf(month);
                pres.setString(2, s);
                pres1.setString(2, s);
                ResultSet rs = pres.executeQuery();
                ResultSet rs1 = pres1.executeQuery();
                while (rs.next()&& rs1.next()) {
                    String month1 = String.valueOf(month);
                    String soluonghd = rs.getString(2);
                    String soluonghd1 = rs1.getString(2);
                    String soluongsp = rs.getString(3);
                    String soluongsp1 = rs1.getString(3);
                    String tongtien = rs.getString(1);
                    String tongtien1 = rs1.getString(1);

                    Object row[] = {month1, year, soluonghd, soluonghd1, soluongsp, soluongsp1,tongtien,tongtien1};
                    tblModel.addRow(row);
                }

                month++;
            }
            jTable1.setModel(tblModel);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datecreatebill = new com.raven.datechooser.DateChooser();
        mainpanel = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new keeptoo.Mybutton();
        jLabel7 = new javax.swing.JLabel();
        panelMedInform14 = new keeptoo.KGradientPanel();
        panelMedInform15 = new keeptoo.KGradientPanel();
        panelMedInform16 = new keeptoo.KGradientPanel();
        panelMedInform17 = new keeptoo.KGradientPanel();
        jnam = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        panelMedInform18 = new keeptoo.KGradientPanel();
        panelMedInform19 = new keeptoo.KGradientPanel();
        panelMedInform20 = new keeptoo.KGradientPanel();
        panelMedInform21 = new keeptoo.KGradientPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        mybutton30 = new keeptoo.Mybutton2();
        jLabel29 = new javax.swing.JLabel();
        mybutton31 = new keeptoo.Mybutton2();
        jLabel25 = new javax.swing.JLabel();
        Incomebutton = new keeptoo.Mybutton2();
        Invoicebutton = new keeptoo.Mybutton2();
        jLabel3 = new javax.swing.JLabel();
        panelReset2 = new keeptoo.KGradientPanel();
        panelReset3 = new keeptoo.KGradientPanel();
        Incomechart = new keeptoo.Mybutton2();
        Invoicechart = new keeptoo.Mybutton2();
        Invoicechart1 = new keeptoo.Mybutton2();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chart1 = new com.raven.chart.Chart();
        jPanel3 = new javax.swing.JPanel();
        chart2 = new com.raven.chart.Chart();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Invoicechart2 = new keeptoo.Mybutton2();
        Invoicechart3 = new keeptoo.Mybutton2();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        datecreatebill.setDateFormat("dd/MM/yyyy");
        datecreatebill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 131, 149));
        setMinimumSize(new java.awt.Dimension(1100, 783));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainpanel.setBackground(new java.awt.Color(10, 77, 105));
        mainpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 15, 0, new java.awt.Color(8, 131, 149)));
        mainpanel.setForeground(new java.awt.Color(10, 77, 105));
        mainpanel.setMaximumSize(new java.awt.Dimension(1200, 750));
        mainpanel.setMinimumSize(new java.awt.Dimension(1101, 750));
        mainpanel.setPreferredSize(new java.awt.Dimension(1101, 750));
        mainpanel.setLayout(null);

        kGradientPanel4.setBackground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setForeground(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setkEndColor(new java.awt.Color(5, 191, 219));
        kGradientPanel4.setkGradientFocus(50);
        kGradientPanel4.setkStartColor(new java.awt.Color(8, 131, 149));
        kGradientPanel4.setMinimumSize(new java.awt.Dimension(20, 690));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(20, 690));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        mainpanel.add(kGradientPanel4);
        kGradientPanel4.setBounds(810, 0, 20, 710);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow.png"))); // NOI18N
        mainpanel.add(jLabel9);
        jLabel9.setBounds(890, 622, 45, 45);

        btnBack.setBorder(null);
        btnBack.setText("      Quay lại");
        btnBack.setColor1(new java.awt.Color(216, 171, 255));
        btnBack.setColor2(new java.awt.Color(3, 137, 255));
        btnBack.setFocusable(false);
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setkGradientFocus(225);
        btnBack.setPreferredSize(new java.awt.Dimension(170, 65));
        btnBack.setRadius(39);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainpanel.add(btnBack);
        btnBack.setBounds(890, 620, 130, 50);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        mainpanel.add(jLabel7);
        jLabel7.setBounds(870, 40, 171, 120);

        panelMedInform14.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform14.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform14.setkGradientFocus(550);
        panelMedInform14.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform14.setLayout(null);

        panelMedInform15.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform15.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform15.setkGradientFocus(550);
        panelMedInform15.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform15.setLayout(null);
        panelMedInform14.add(panelMedInform15);
        panelMedInform15.setBounds(450, 440, 330, 170);

        panelMedInform16.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform16.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform16.setkGradientFocus(550);
        panelMedInform16.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform16.setLayout(null);

        panelMedInform17.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform17.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform17.setkGradientFocus(550);
        panelMedInform17.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform17.setLayout(null);
        panelMedInform16.add(panelMedInform17);
        panelMedInform17.setBounds(450, 440, 330, 170);

        panelMedInform14.add(panelMedInform16);
        panelMedInform16.setBounds(470, 480, 330, 170);

        jnam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelMedInform14.add(jnam);
        jnam.setBounds(130, 40, 100, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nhập năm");
        jLabel24.setToolTipText("");
        panelMedInform14.add(jLabel24);
        jLabel24.setBounds(30, 40, 80, 16);

        panelMedInform18.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform18.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform18.setkGradientFocus(550);
        panelMedInform18.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform18.setLayout(null);

        panelMedInform19.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform19.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform19.setkGradientFocus(550);
        panelMedInform19.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform19.setLayout(null);
        panelMedInform18.add(panelMedInform19);
        panelMedInform19.setBounds(450, 440, 330, 170);

        panelMedInform20.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform20.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform20.setkGradientFocus(550);
        panelMedInform20.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform20.setLayout(null);

        panelMedInform21.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelMedInform21.setkEndColor(new java.awt.Color(16, 123, 162));
        panelMedInform21.setkGradientFocus(550);
        panelMedInform21.setkStartColor(new java.awt.Color(16, 123, 162));
        panelMedInform21.setLayout(null);
        panelMedInform20.add(panelMedInform21);
        panelMedInform21.setBounds(450, 440, 330, 170);

        panelMedInform18.add(panelMedInform20);
        panelMedInform20.setBounds(470, 480, 330, 170);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Giảm giá");
        panelMedInform18.add(jLabel26);
        jLabel26.setBounds(60, 60, 80, 20);

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField18.setText("0");
        panelMedInform18.add(jTextField18);
        jTextField18.setBounds(200, 60, 100, 23);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Khách cần trả");
        jLabel27.setToolTipText("");
        panelMedInform18.add(jLabel27);
        jLabel27.setBounds(60, 100, 100, 16);

        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelMedInform18.add(jTextField19);
        jTextField19.setBounds(200, 100, 100, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tổng tiền");
        jLabel28.setToolTipText("");
        panelMedInform18.add(jLabel28);
        jLabel28.setBounds(60, 20, 70, 16);

        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelMedInform18.add(jTextField20);
        jTextField20.setBounds(200, 20, 100, 22);

        mybutton30.setBorder(null);
        mybutton30.setText("Tính");
        mybutton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mybutton30.setRadius(35);
        panelMedInform18.add(mybutton30);
        mybutton30.setBounds(80, 140, 100, 30);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        panelMedInform18.add(jLabel29);
        jLabel29.setBounds(10, 130, 41, 41);

        mybutton31.setBorder(null);
        mybutton31.setText("Lưu");
        mybutton31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mybutton31.setRadius(35);
        panelMedInform18.add(mybutton31);
        mybutton31.setBounds(240, 140, 100, 30);

        panelMedInform14.add(panelMedInform18);
        panelMedInform18.setBounds(390, 450, 390, 180);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine2 (3).png"))); // NOI18N
        panelMedInform14.add(jLabel25);
        jLabel25.setBounds(250, 40, 41, 41);

        Incomebutton.setBorder(null);
        Incomebutton.setText("Thống kê doanh thu");
        Incomebutton.setFocusable(false);
        Incomebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Incomebutton.setRadius(35);
        Incomebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomebuttonActionPerformed(evt);
            }
        });
        panelMedInform14.add(Incomebutton);
        Incomebutton.setBounds(320, 30, 150, 40);

        Invoicebutton.setBorder(null);
        Invoicebutton.setText("Thống kê hóa đơn");
        Invoicebutton.setFocusable(false);
        Invoicebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Invoicebutton.setRadius(35);
        Invoicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoicebuttonActionPerformed(evt);
            }
        });
        panelMedInform14.add(Invoicebutton);
        Invoicebutton.setBounds(500, 30, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        panelMedInform14.add(jLabel3);
        jLabel3.setBounds(700, 40, 41, 41);

        mainpanel.add(panelMedInform14);
        panelMedInform14.setBounds(20, 560, 760, 90);

        panelReset2.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelReset2.setkEndColor(new java.awt.Color(16, 123, 162));
        panelReset2.setkGradientFocus(550);
        panelReset2.setkStartColor(new java.awt.Color(16, 123, 162));
        panelReset2.setLayout(null);

        panelReset3.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(5, 191, 219)));
        panelReset3.setkEndColor(new java.awt.Color(16, 123, 162));
        panelReset3.setkGradientFocus(550);
        panelReset3.setkStartColor(new java.awt.Color(16, 123, 162));
        panelReset3.setLayout(null);
        panelReset2.add(panelReset3);
        panelReset3.setBounds(830, 410, 250, 100);

        Incomechart.setBorder(null);
        Incomechart.setText("Biểu đồ doanh thu");
        Incomechart.setFocusable(false);
        Incomechart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Incomechart.setRadius(35);
        Incomechart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomechartActionPerformed(evt);
            }
        });
        panelReset2.add(Incomechart);
        Incomechart.setBounds(50, 20, 150, 40);

        Invoicechart.setBorder(null);
        Invoicechart.setText("Biểu đồ hóa đơn");
        Invoicechart.setFocusable(false);
        Invoicechart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Invoicechart.setRadius(35);
        Invoicechart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoicechartActionPerformed(evt);
            }
        });
        panelReset2.add(Invoicechart);
        Invoicechart.setBounds(50, 80, 150, 40);

        Invoicechart1.setBorder(null);
        Invoicechart1.setText("Thống kê");
        Invoicechart1.setFocusable(false);
        Invoicechart1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Invoicechart1.setRadius(35);
        Invoicechart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoicechart1ActionPerformed(evt);
            }
        });
        panelReset2.add(Invoicechart1);
        Invoicechart1.setBounds(50, 140, 150, 40);

        mainpanel.add(panelReset2);
        panelReset2.setBounds(830, 290, 250, 200);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 0, 6, 0, new java.awt.Color(5, 191, 219)));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thống kê doanh thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        mainpanel.add(jPanel1);
        jPanel1.setBounds(830, 180, 250, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (2).png"))); // NOI18N
        mainpanel.add(jLabel16);
        jLabel16.setBounds(870, 250, 40, 41);

        jTabbedPane1.setBackground(new java.awt.Color(10, 77, 105));
        jTabbedPane1.setForeground(new java.awt.Color(10, 77, 105));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(10, 77, 105));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 77, 105)));
        jPanel2.setForeground(new java.awt.Color(10, 77, 105));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIểu đồ doanh thu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(10, 77, 105));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        chart2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Biểu đồ hóa đơn theo tháng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel5)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(10, 77, 105));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thống kê doanh thu và hóa đơn theo năm");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Invoicechart2.setBorder(null);
        Invoicechart2.setText("Tải dữ liệu");
        Invoicechart2.setFocusable(false);
        Invoicechart2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Invoicechart2.setRadius(35);
        Invoicechart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoicechart2ActionPerformed(evt);
            }
        });

        Invoicechart3.setBorder(null);
        Invoicechart3.setText("In báo cáo");
        Invoicechart3.setFocusable(false);
        Invoicechart3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Invoicechart3.setRadius(35);
        Invoicechart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoicechart3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Invoicechart2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Invoicechart3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Invoicechart2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Invoicechart3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        mainpanel.add(jTabbedPane1);
        jTabbedPane1.setBounds(-50, 10, 860, 550);

        jPanel6.setBackground(new java.awt.Color(8, 131, 149));
        jPanel6.setPreferredSize(new java.awt.Dimension(290, 95));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.add(jPanel6);
        jPanel6.setBounds(830, 490, 250, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine3 (1).png"))); // NOI18N
        mainpanel.add(jLabel4);
        jLabel4.setBounds(940, 250, 41, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (VAITRO.equals("0")) {
            this.dispose();
            ManagerDashBoard m = new ManagerDashBoard();
            m.setVisible(true);
        } else if (VAITRO.equals("1")) {
            this.dispose();
            EmpDashBoard m = new EmpDashBoard();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void IncomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomebuttonActionPerformed
        chart1.clear();
        Connection conn = new DBUtils().createConn();
        String year = jnam.getText();
        try {
            int month = 1;
            while (month <= 12) {
                String sql = "select sum(TRIGIA) from HOADON where extract(year from NGHD)= ? and extract(month from NGHD)= ?";
                String sql1= "select sum(TRIGIA) from HOADONNHAP where extract(year from NGHDN)= ? and extract(month from NGHDN)= ?";
                PreparedStatement pres = conn.prepareStatement(sql);
                PreparedStatement pres1 = conn.prepareStatement(sql1);
                pres.setString(1, year);
                pres1.setString(1, year);
                String s = String.valueOf(month);
                pres.setString(2, s);
                pres1.setString(2, s);
                ResultSet rs = pres.executeQuery();
                ResultSet rs1 = pres1.executeQuery();
                double a=0,b=1000000;
                while (rs.next() && rs1.next()) {
                    a = rs.getDouble(1);
                    b = rs1.getDouble(1);
                    chart1.addData(new ModelChart(s, new double[]{a,b}));
                }
                month++;
            }
            chart1.start();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_IncomebuttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        chart1.start();
    }//GEN-LAST:event_formWindowOpened

    private void InvoicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoicebuttonActionPerformed
        // TODO add your handling code here:
        chart2.clear();
        Connection conn = new DBUtils().createConn();
        String year = jnam.getText();
        try {
            int month = 1;
            while (month <= 12) {
                String sql = "select count(SOHD) from HOADON where extract(year from NGHD)= ? and extract(month from NGHD)= ?";
                String sql1 = "select count(SOHDN) from HOADONNHAP where extract(year from NGHDN)= ? and extract(month from NGHDN)= ?";
                PreparedStatement pres = conn.prepareStatement(sql);
                PreparedStatement pres1 = conn.prepareStatement(sql1);
                pres.setString(1, year);
                pres1.setString(1, year);
                String s = String.valueOf(month);
                pres.setString(2, s);
                pres1.setString(2, s);
                ResultSet rs = pres.executeQuery();
                ResultSet rs1 = pres1.executeQuery();
                while (rs.next()&& rs1.next()) {
                    double a = rs.getDouble(1);
                    double b = rs1.getDouble(1);
                    chart2.addData(new ModelChart(s, new double[]{a,b}));

                }
                month++;
            }
            chart2.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_InvoicebuttonActionPerformed

    private void InvoicechartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoicechartActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_InvoicechartActionPerformed

    private void IncomechartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomechartActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_IncomechartActionPerformed

    private void Invoicechart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoicechart1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_Invoicechart1ActionPerformed

    private void Invoicechart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoicechart2ActionPerformed
        // TODO add your handling code here:
        Loaddata(jnam.getText());
    }//GEN-LAST:event_Invoicechart2ActionPerformed

    private void Invoicechart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoicechart3ActionPerformed
        // TODO add your handling code here:
        PrintRevenue();
    }//GEN-LAST:event_Invoicechart3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevenueStatistics().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.Mybutton2 Incomebutton;
    private keeptoo.Mybutton2 Incomechart;
    private keeptoo.Mybutton2 Invoicebutton;
    private keeptoo.Mybutton2 Invoicechart;
    private keeptoo.Mybutton2 Invoicechart1;
    private keeptoo.Mybutton2 Invoicechart2;
    private keeptoo.Mybutton2 Invoicechart3;
    private keeptoo.Mybutton btnBack;
    private com.raven.chart.Chart chart1;
    private com.raven.chart.Chart chart2;
    private com.raven.datechooser.DateChooser datecreatebill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jnam;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JPanel mainpanel;
    private keeptoo.Mybutton2 mybutton30;
    private keeptoo.Mybutton2 mybutton31;
    private keeptoo.KGradientPanel panelMedInform14;
    private keeptoo.KGradientPanel panelMedInform15;
    private keeptoo.KGradientPanel panelMedInform16;
    private keeptoo.KGradientPanel panelMedInform17;
    private keeptoo.KGradientPanel panelMedInform18;
    private keeptoo.KGradientPanel panelMedInform19;
    private keeptoo.KGradientPanel panelMedInform20;
    private keeptoo.KGradientPanel panelMedInform21;
    private keeptoo.KGradientPanel panelReset2;
    private keeptoo.KGradientPanel panelReset3;
    // End of variables declaration//GEN-END:variables
}
